#!/usr/bin/env python

import flickrapi
import requests

#Using a token generated in auth_private_flickr.py this script downloads private photo files.

FLICKR_KEY = "******"
FLICKR_SECRET = "*****"
AUTH_TOKEN = "******"   #Auth token generated by auth_private_flickr.py
USER_ID = "******"
TAGS = "photoframe"  #Example code uses tags to download private photos.

def make_url(photo):
    photo['filename'] = "%(id)s_o-%(secret)s_o.jpg" % photo
    url = photo['url_o']
    return url, photo['filename']

def main():
    print " ---> Requesting photos..."
    flickr = flickrapi.FlickrAPI(FLICKR_KEY,FLICKR_SECRET,token=AUTH_TOKEN,store_token=True)
    photos = flickr.photos_search(user_id=USER_ID, tags="photoframe",extras="url_o")
    print photos
    for photo in photos.find('photos'):
        url, filename = make_url(photo.__dict__['attrib'])
        path = '/home/pi/photoframe/flickr/%s' % filename
        try:
            image_file = open(path)
            print " ---> Already have %s" % url
        except IOError:
            print " ---> Downloading %s" % url
            r = requests.get(url)      
            image_file = open(path, 'w')
            image_file.write(r.content)
            image_file.close()
            
if __name__ == '__main__':
    main()
